version: '3.8'

services:
  sqlserver:
    container_name: rayo_sql_server
    image: mcr.microsoft.com/azure-sql-edge
    platform: linux/arm64  # Mac M1
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=RayoCinema3!
    ports:
      - "1433:1433"

  backend:
    container_name: rayo_backend
    build:
      context: .
      dockerfile: Dockerfile
      platform: linux/arm64
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
